### ISSUE TITLE
ModuleNotFoundError: No module named 'babble'

### ISSUE THREAD

**Issue by SkySailing** [vantaworks/python-pex-tutorial#1]
after follow the code in chapter 2:Embedding more complicated apps.
get the output

```
Traceback (most recent call last):
  File "/Users/zhangsan/opt/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/zhangsan/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/__main__.py", line 103, in <module>
    bootstrap_pex(__entry_point__, execute=__execute__, venv_dir=__venv_dir__)
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/.bootstrap/pex/pex_bootstrapper.py", line 601, in bootstrap_pex
    pex.PEX(entry_point).execute()
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/.bootstrap/pex/pex.py", line 540, in execute
    sys.exit(self._wrap_coverage(self._wrap_profiling, self._execute))
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/.bootstrap/pex/pex.py", line 447, in _wrap_coverage
    return runner(*args)
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/.bootstrap/pex/pex.py", line 478, in _wrap_profiling
    return runner(*args)
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/.bootstrap/pex/pex.py", line 567, in _execute
    return self.execute_entry(
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/.bootstrap/pex/pex.py", line 749, in execute_entry
    return self.execute_entry_point(entry_point)
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/.bootstrap/pex/pex.py", line 766, in execute_entry_point
    runner = entry_point.resolve()
  File "/Users/zhangsan/.pex/unzipped_pexes/91dc0383d414a80b949b8e4b1404a3ea7be966ad/.bootstrap/pex/dist_metadata.py", line 724, in resolve
    module = importlib.import_module(self.module)
  File "/Users/zhangsan/opt/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'babble'
```

**Comment by h4110w33n** [comment]
The error indicates `pex` builder can't address the `babble` module. Let's check to see if it is _installed_ right. From that same section, it would be the following command: 

`python setup.py develop`

If you've ran that already and you hit the same error when trying to compile, then we should check these two things next:

1. Could you run `pip freeze` or `pip list` to see if the babble module is installed?
2. If `babble` (version 0.1) is installed, could you enter into an interactive Python shell and try to import it? As in: `import babble`

**Comment by SkySailing** [comment]
i fix this bug by this, build the pex file by following code.

```
pex -r requirements.txt  -f . babble --disable-cache  -o babble.pex -e babble:launcher
```
`-f . babble` to find the package from the current path.
